app/urls.py
from django.conf.urls import url
from app import views

app_name = "app"

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^about/$', views.about, name="about"),
    url(r'^all_user/$', views.all_user, name="all_user"),
    url(r'^detail_user/(?P<pk>\d+)$', views.detail_user, name="detail_user"),
    url(r'^findus/$', views.findus, name="findus"),
    url(r'^represent/$', views.represent, name="represent"),
    url(r'^calender/$', views.calender, name="calender"),
    url(r'^status/(?P<pk>\d+)/show/$', views.show_status, name="show_status"),
    url(r'^terms_condition/$', views.terms_condition, name="terms_condition"),
    url(r'^faq/$', views.faq, name="faq"),
    url(r'^damage_charges/$', views.damage_charges, name="damage_charges"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),

]

pay/urls.py
from django.conf.urls import url
from pay.views import (cart, payment_success, payment_failure)

app_name = "pay"

urlpatterns = [
    url(r'^$', cart, name="pay"),
    url(r'^success/$', payment_success, name="success"),
    url(r'^failure/$', payment_failure, name="failure"),
]

vehicle/urls.py
from django.conf.urls import url
from vehicle.views import (vehicles, vehicle_create_check,
                           vehicle_update_check, vehicle_info,vehicle)

app_name = "vehicles"

urlpatterns = [
    url(r'^$', vehicles, name="vehicles"),
    url(r'^(?P<pk>\d+)/create/$', vehicle_create_check, name="vehicle_create_check"),
    url(r'^(?P<pk>\d+)/update/$', vehicle_update_check, name="vehicle_update_check"),
    url(r'^vehicle_info/$', vehicle_info, name="vehicle_info"),
    url(r'^all/$', vehicle, name="vehicle"),
]

vehicle/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class VehicleCheck(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="vehicle_check",
                             null=True, blank=True)
    engine_oil_level = models.PositiveIntegerField()
    brake_fluid_level = models.PositiveIntegerField()
    water_level = models.PositiveIntegerField()
    windscreen_washer = models.BooleanField()
    seatbelts_check = models.BooleanField()
    parking_brake = models.BooleanField()
    clutch_gearshift = models.BooleanField()
    burning_smell = models.BooleanField()
    steering_alignment = models.BooleanField()
    dashboard = models.BooleanField()
    check_lights = models.BooleanField()
    horn = models.BooleanField()
    tyres = models.BooleanField()
    leakage = models.BooleanField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


class Definition(models.Model):
    car_name = models.CharField(max_length=64, blank=True, null=True)
    car_type = models.CharField(max_length=64, blank=True, null=True)
    seat = models.CharField(max_length=12, blank=True, null=True)
    year = models.CharField(max_length=4, blank=True, null=True)
    color = models.CharField(max_length=12, blank=True, null=True)
    car_image = models.ImageField(upload_to="cars", blank=True, null=True)

    def __str__(self):
        return self.car_name


class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    definition = models.ForeignKey(Definition, on_delete=models.CASCADE, null=True, blank=True)
    car_name = models.CharField(max_length=64, blank=True, null=True)
    check_in_date = models.DateField(blank=True, null=True)
    check_out_date = models.DateField(blank=True, null=True)
    duration = models.IntegerField()
    txnid = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.car_name + ' ' + str(self.duration)

vehicle/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from vehicle.models import VehicleCheck
from vehicle.models import Definition, Book
from django.contrib import messages
import datetime
from datetime import date


# Create your views here.

def single_car_book(name,now,check_in,check_out):
    definition = Definition.objects.filter(car_type=name)
    for _ in definition:
        book = Book.objects.filter(definition=_, check_in_date__gte=now)
        if book.count() == 0:
            return _
        for b in book:
            if check_in < b.check_in_date and check_out < b.check_in_date or check_in > b.check_out_date \
                    and check_out > b.check_out_date:
                return _

            else:
                return {}


def vehicles(request):
    list1 = []
    now = date.today()
    try:
        d0 = request.GET.get("tripDay").replace("-", "")
    except:
        return redirect("app:home")
    duration = request.GET.get("Duration")
    check_in = datetime.datetime.strptime(d0, "%Y%m%d").date()
    check_out = check_in + datetime.timedelta(int(duration))

    if check_in < now:
        messages.warning(request, "cant book the car for past date")
        return redirect("app:home")

    definition = Definition.objects.filter(car_type="xenon_soft")
    for _ in definition:
        book = Book.objects.filter(definition=_, check_in_date__gte=now)
        if book.count() == 0:
            xenon_soft = _
            break
        for b in book:
            if check_in < b.check_in_date and check_out < b.check_in_date or check_in > b.check_out_date \
                    and check_out > b.check_out_date:#  here i am checking for booked for range which is booked for, meaning past dates does not matter it will always make it 1
                list1.append(1)
            else:
                list1.append(0)
        if 0 in list1:
            xenon_soft = {}
        else:
            xenon_soft = _
            break
        list1 = []

    thar = single_car_book(name="thar", now=now, check_in=check_in, check_out=check_out)
    xenon_hard = single_car_book(name="xenon_hard", now=now, check_in=check_in,check_out=check_out)
    caravan = single_car_book(name="caravan", now=now, check_in=check_in, check_out=check_out)
    data = {
        "thar": thar,
        "xenon_soft": xenon_soft,
        "xenon_hard": xenon_hard,
        "caravan": caravan,
    }
    return render(request, "vehicle/vehicles.html", data)


def vehicle_info(request):
    return render(request, "vehicle/vehicle_info.html")


def vehicle(request):
    return render(request, "vehicle/vehicle.html")


def vehicle_create_check(request, pk):
    users = User.objects.get(id=pk)
    if request.method == "POST":
        engine_oil_level = request.POST.get("engine_oil")
        brake_fluid_level = request.POST.get("brake_fluid")
        water_level = request.POST.get("water_level")
        windscreen_washer = request.POST.get("windscreen")
        seatbelts_check = request.POST.get("seatbelts")
        parking_brake = request.POST.get("parking")
        clutch_gearshift = request.POST.get("clutch")
        burning_smell = request.POST.get("burning")
        steering_alignment = request.POST.get("steering")
        dashboard = request.POST.get("dashboard")
        check_lights = request.POST.get("check_lights")
        horn = request.POST.get("horn")
        tyres = request.POST.get("tyres")
        leakage = request.POST.get("leakage")

        vehicle = VehicleCheck(user=users, engine_oil_level=engine_oil_level,
                               brake_fluid_level=brake_fluid_level, water_level=water_level,
                               windscreen_washer=windscreen_washer, seatbelts_check=seatbelts_check,
                               parking_brake=parking_brake, clutch_gearshift=clutch_gearshift,
                               burning_smell=burning_smell, steering_alignment=steering_alignment,
                               dashboard=dashboard, check_lights=check_lights, horn=horn, tyres=tyres,
                               leakage=leakage)
        vehicle.save()
        return redirect("app:show_status", pk=users.pk)
    else:
        return render(request, "vehicle/vehicle_create_check.html")


def vehicle_update_check(request, pk):
    vehicle = VehicleCheck.objects.get(pk=pk, active=True)
    if request.method == "POST":
        users = User.objects.get(pk=vehicle.user.pk)
        engine_oil_level = request.POST.get("engine_oil")
        brake_fluid_level = request.POST.get("water_level")
        water_level = request.POST.get("brake_fluid")
        windscreen_washer = request.POST.get("windscreen")
        seatbelts_check = request.POST.get("seatbelts")
        parking_brake = request.POST.get("parking")
        clutch_gearshift = request.POST.get("clutch")
        burning_smell = request.POST.get("burning")
        steering_alignment = request.POST.get("steering")
        dashboard = request.POST.get("dashboard")
        check_lights = request.POST.get("check_lights")
        horn = request.POST.get("horn")
        tyres = request.POST.get("tyres")
        leakage = request.POST.get("leakage")

        VehicleCheck.objects.filter(pk=pk).update(user=users, engine_oil_level=engine_oil_level,
                                                  brake_fluid_level=brake_fluid_level, water_level=water_level,
                                                  windscreen_washer=windscreen_washer, seatbelts_check=seatbelts_check,
                                                  parking_brake=parking_brake, clutch_gearshift=clutch_gearshift,
                                                  burning_smell=burning_smell, steering_alignment=steering_alignment,
                                                  dashboard=dashboard, check_lights=check_lights, horn=horn, tyres=tyres,
                                                  leakage=leakage)

        return redirect("app:show_status", pk=users.pk)

    else:
        return render(request, "vehicle/vehicle_update_check.html", {"vehicle": vehicle})

vehicle/templates/vehicle/vehicle.html
{% extends "snippets/base.html" %}
    {% load staticfiles %} {% block css %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.0.1/tailwind.min.css">
    {% endblock %}
{% block title %}
    <title>Book Your dream Holiday.</title>
{% endblock %}
{% block meta %}
<meta name="description" content="Book our purpose-built overland campers to tour Northeast India and Bhutan. You can camp in remote locations with stunning views in the rooftop tents attached on the vehicles. Explore unique destinations, communities, and culture in Northeast India and Bhutan with Camping Co.’s pioneering self-drive overland travel form.">
<meta name="keywords" content="vehicles for camping, vehicles for camping company, camping vehicles northeast, rooftop tent vehicle , rent a vehicle meghalaya, overlanding car thar, modified vehicles northeast, cheapest camping vehicle, guwahati camping vehicle rent">
{% endblock %}
{% block content_block %}
<br>
<br>
<br>
    <div class="max-w-6xl mx-auto">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({% static 'images/thar11.jpg' %});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Thar</p>
                        <p class="text-3xl text-gray-900">INR 2999*</p>
                        <p class="text-gray-700">4x4</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                            <div>
                                <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                    <button id="btn-thar" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                                </form>
                                <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({% static 'images/SSS03663.jpg' %});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Xenon soft top tent</p>
                        <p class="text-3xl text-gray-900">INR 2999*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                          <div>
                              <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                  <button id="btn-thar" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                              </form>
                              <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({% static 'images/hard1.jpg' %});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Xenon hard top tent</p>
                        <p class="text-3xl text-gray-900">INR 3299*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                          <div>
                              <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                  <button id="btn-thar" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                              </form>
                              <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({% static 'images/cara3.jpeg' %});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Caravan</p>
                        <p class="text-3xl text-gray-900">INR 7599*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                          <div>
                              <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                  <button id="btn-thar" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                              </form>
                              <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

vehicle/templates/vehicle/vehicles.html
{% extends "snippets/base.html" %}
    {% load staticfiles %} {% block css %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.0.1/tailwind.min.css">
    {% endblock %}
{% block title %}
    <title>Book Your dream Holiday.</title>
{% endblock %}
{% block meta %}
<meta name="description" content="Book our purpose-built overland campers to tour Northeast India and Bhutan. You can camp in remote locations with stunning views in the rooftop tents attached on the vehicles. Explore unique destinations, communities, and culture in Northeast India and Bhutan with Camping Co.’s pioneering self-drive overland travel form.">
<meta name="keywords" content="vehicles for camping, vehicles for camping company, camping vehicles northeast, rooftop tent vehicle , rent a vehicle meghalaya, overlanding car thar, modified vehicles northeast, cheapest camping vehicle, guwahati camping vehicle rent">
{% endblock %}
{% block content_block %}
<br>
<br>
<br>
{% if xenon_soft or thar or xenon_hard or caravan %}
    <div class="max-w-6xl mx-auto">
        <div class="row">
            {% if thar %}
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({{thar.car_image.url}});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">{{thar.car_type}}</p>
                        <p class="text-3xl text-gray-900">INR 2999*</p>
                        <p class="text-gray-700">4x4</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                            <div>
                                <input class="sib" hidden name="id" value="{{thar.pk}}">
                                <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                    <input hidden name="status" value="true" class="status">
                                    <input hidden name="price" value="2999">
                                    <button id="btn-thar" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                                </form>
                                <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if xenon_soft %}
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({{xenon_soft.car_image.url}});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Xenon soft top tent</p>
                        <p class="text-3xl text-gray-900">INR 2999*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                            <div>
                                <input class="sib" hidden name="id" value="{{xenon_soft.pk}}">
                                <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                    <input hidden name="status" value="true" class="status">
                                    <input hidden name="price" value="2999">
                                    <button id="btn-xenon-soft" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                                </form>
                                <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% if xenon_hard %}
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({{xenon_hard.car_image.url}});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Xenon hard top tent</p>
                        <p class="text-3xl text-gray-900">INR 3299*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                            <div>
                                <input class="sib" hidden name="id" value="{{xenon_hard.pk}}">
                                <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                    <input hidden name="status" value="true" class="status">
                                    <input hidden name="price" value="3299">
                                    <button id="btn-xenon-hard" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                                </form>
                                <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% if caravan %}
            <div class="col-sm-12 col-md-6 col-lg-4 pt-6 p-6">
                <div class="bg-white shadow-xl rounded-lg overflow-hidden">
                    <div class="bg-cover bg-center h-56 p-4" style="background-image: url({{caravan.car_image.url}});">
                        <div class="flex justify-end">
                            <svg class="h-6 w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12.76 3.76a6 6 0 0 1 8.48 8.48l-8.53 8.54a1 1 0 0 1-1.42 0l-8.53-8.54a6 6 0 0 1 8.48-8.48l.76.75.76-.75zm7.07 7.07a4 4 0 1 0-5.66-5.66l-1.46 1.47a1 1 0 0 1-1.42 0L9.83 5.17a4 4 0 1 0-5.66 5.66L12 18.66l7.83-7.83z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="p-4">
                        <p class="uppercase tracking-wide text-sm font-bold text-gray-700">Caravan</p>
                        <p class="text-3xl text-gray-900">INR 7599*</p>
                        <p class="text-gray-700">4x2</p>
                    </div>
                    <div class="px-4 pt-3 pb-4 border-t border-gray-300 bg-gray-100">
                        <div class="flex items-center pt-2">
                            <div>
                                <input class="sib" hidden name="id" value="{{caravan.pk}}">
                                <form style="display:inline-block" action="{% url 'pay:pay' %}" method="POST">{% csrf_token %}
                                    <input hidden name="status" value="true" class="status">
                                    <input hidden name="price" value="7599">
                                    <button id="btn-caravan" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Book Now</button>
                                </form>
                                <button onclick= "location.href = '{% url 'vehicle:vehicle_info'%}';" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">More Info</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}


        </div>
    </div>
{% else %}
<h1 style="text-align: center">No car available</h1>
{% endif %}
<br>
<script>
window.onload = function() {
    var queryDict = {}
    var check_in;

    var x1 = "{{thar.car_type}}";
    var x2 = "{{thar.car_name}}";

    var y1 = "{{xenon_soft.car_type}}";
    var y2 = "{{xenon_soft.car_name}}";

    var z1 = "{{xenon_hard.car_type}}";
    var z2 = "{{xenon_hard.car_name}}";

    var c1 = "{{caravan.car_type}}";
    var c2 = "{{caravan.car_name}}";


    location.search.substr(1).split("&").forEach(function(item) {queryDict[item.split("=")[0]] = item.split("=")[1]})
    localStorage.setItem("duration", queryDict["Duration"]);
    localStorage.setItem("check_in", queryDict["tripDay"]);

    $("#btn-thar").click(function(){
        localStorage.setItem("car_type", x1);
        localStorage.setItem("car_name", x2);
    })

    $("#btn-xenon-soft").click(function(){
        localStorage.setItem("car_type", y1);
        localStorage.setItem("car_name", y2);
    })

    $("#btn-xenon-hard").click(function(){
        localStorage.setItem("car_type", z1);
        localStorage.setItem("car_name", z2);
    })

    $("#btn-caravan").click(function(){
        localStorage.setItem("car_type", c1);
        localStorage.setItem("car_name", c2);
    })
    }
</script>
{% endblock %}

<!--<script>-->
    <!--$(".datetimepicker").datetimepicker({-->
     <!--timepicker:false,-->
     <!--format:'d.m.Y'-->
     <!--});-->
<!--</script>-->