app/urls.py
from django.conf.urls import url
from app import views

app_name = "app"

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^about/$', views.about, name="about"),
    url(r'^all_user/$', views.all_user, name="all_user"),
    url(r'^detail_user/(?P<pk>\d+)$', views.detail_user, name="detail_user"),
    url(r'^findus/$', views.findus, name="findus"),
    url(r'^represent/$', views.represent, name="represent"),
    url(r'^calender/$', views.calender, name="calender"),
    url(r'^status/(?P<pk>\d+)/show/$', views.show_status, name="show_status"),
    url(r'^terms_condition/$', views.terms_condition, name="terms_condition"),
    url(r'^faq/$', views.faq, name="faq"),
    url(r'^damage_charges/$', views.damage_charges, name="damage_charges"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),

]

register/urls.py
from django.conf.urls import url
from register.views import (signup, signin, sign_out,
                            welcome, pass_reset,pass_rediretor)


app_name = "register"

urlpatterns = [
    url(r'^signup/$', signup, name="signup"),
    url(r'^login/$', signin, name="signin"),
    url(r'^logout/$', sign_out, name="signout"),
    url(r'^welcome/$', welcome, name="welcome"),
    url(r'^reset/(?P<slug>[\w-]+)/$', pass_rediretor, name="pass_rediretor"),
    url(r'^reset/$', pass_reset, name="pass_reset"),

]

register/models.py
from django.db import models
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from django.urls import reverse


class Password(models.Model):
    email = models.EmailField(max_length=128)
    slug = models.SlugField(blank=True, unique=True)
    reset_link = models.CharField(max_length=64, blank=True, null=True)
    initiate_date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)
    used = models.BooleanField(default=False)

    def __str__(self):
        return self.email


def referral_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
        instance.reset_link = "https://www.camping-co.com" + reverse("register:pass_reset") + instance.slug

pre_save.connect(referral_pre_save_receiver, sender=Password)

register/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from customer.models import Customer
from django.contrib import messages
from referral.models import Referral
from app.utils import *
from pay.models import Pay
import re
from django.utils.http import is_safe_url
from django.http import JsonResponse
from register.models import Password
from datetime import date

# Create your views here.


def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        user_n = User.objects.filter(username=username)
        user_e = User.objects.filter(email=email)
        password1 = request.POST.get("password1")
        code = request.POST.get("slug")

        if user_n.count() == 1 or user_e.count() == 1:
            messages.warning(request, "Username/email already taken or log in to complete signup")
            return redirect("register:signin")

        if code is "":

            '''If referral code is empty'''
            user = User.objects.create_user(username=username, email=email)
            Referral(user=user).save()
            user.set_password(password1)
            user.save()
            login(request, user)
            Pay(user=user, email=email).save()
            #Customer(user=user).save()
            return redirect("register:welcome")
        try:
            ref_user = Referral.objects.get(slug=code)
        except:
            messages.warning(request, "Wrong referral code")
            return redirect("register:signin")

        '''If referral code is not empty'''
        user = User.objects.create_user(username=username, email=email)
        referral = Referral(user=user, referred_by=ref_user.user, referred=True)
        ref_user.referred_users.add(user)
        user.set_password(password1)
        user.save()
        referral.save()
        ref_user.save()
        login(request, user)
        Pay(user=user, email=email).save()
        #Customer(user=user).save()
        message_to_customer(email)

        return redirect("register:welcome")

    else:
        return render(request, "register/signin.html")


def signin(request):
    next_ = request.GET.get('next')
    if request.method == "POST":
        next_post = request.POST.get('next')
        next_post = next_post.replace("k", "/")
        username = request.POST.get("username")
        password = request.POST.get("password")

        if re.search("@", username):
            try:
                u = User.objects.get(email=username)
                user = authenticate(username=u.username, password=password)
            except:
                messages.warning(request, "You Need to sign up first")
                return redirect("app:home")
        else:
            user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_superuser:
                login(request, user)
                return redirect("app:represent")
            else:
                customer = Customer.objects.filter(user=user)
                if customer.count() == 1:
                    login(request, user)
                    messages.success(request, "Logged in")
                    request.session["user_pk"] = user.pk
                else:
                    login(request, user)
                    messages.warning(request, "Complete sign up")
                    return redirect("register:welcome")

                if next_post != "None":  # not used is_safe_url  here next post is none (a string)
                    return redirect(next_post)
                else:
                    return redirect("customer:user_page")
        else:
            messages.warning(request, "Password/Username is wrong")
            return redirect("register:signin")
    return render(request, "register/signin.html", {"next": next_})


@login_required
def sign_out(request):
    logout(request)
    return redirect("app:home")


@login_required
def welcome(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user.username)
        license_number = request.POST.get("license_number")
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        number = request.POST.get("number")
        city = request.POST.get("city")
        nickname = request.POST.get("nickname")
        about = request.POST.get("about")
        address = request.POST.get("address")
        user.first_name = fname
        user.last_name = lname
        user.number = number
        user.save()
        customer = Customer(user=user, phone=number, city=city,
                            address=address, nickname=nickname,
                            license_number=license_number, about=about,
                            terms_condition=True)
        customer.save()
        message_to_company(email=user.email, message="someone signed up yay!! :)",
                           name=fname, phone=number,
                           subject="Leads Team Rock and Roll")

        Pay.objects.filter(user=user).update(firstname=fname, phone=number)

        return redirect("customer:user_page")
    return render(request, "register/welcome.html")


def pass_reset(request):

    if request.is_ajax():
        email = request.POST.get("email")
        try:
            user = User.objects.get(email=email)
        except:
            return JsonResponse({"error":"User does not exist"})
        password = Password(email=email)
        password.save()
        print()
        password_reset(name=user.first_name,email=email,subject="Password reset",link=password.reset_link)
        return JsonResponse({"success":"success"})

    slug = request.session.get("slug")

    if request.method == "POST":
        pass_resettor = Password.objects.get(slug=slug)
        user = User.objects.get(email=pass_resettor.email)
        password = request.POST.get("password1")
        user.set_password(password)
        user.save()
        pass_resettor.active = False
        pass_resettor.save()
        messages.success(request,"Password change successfully")
        return redirect("app:home")

    try:
        pass_resettor = Password.objects.get(slug=slug)
        if not pass_resettor.active and pass_resettor.used:
            del request.session["slug"]
    except:
        return render(request, "register/pass_reset.html",{"pass_resettor":{"used":False}})
    return render(request, "register/pass_reset.html",{"pass_resettor":pass_resettor})


def pass_rediretor(request,slug):
    now = date.today()
    pass_resettor = Password.objects.get(slug=slug)
    request.session["slug"] = slug
    if pass_resettor.initiate_date == now:
        pass_resettor.used = True
        pass_resettor.save()
        return redirect("register:pass_reset")
    else:
        pass_resettor.active = False
        pass_resettor.save()
    return redirect("register:pass_reset")

register/templates/register/pass_reset.html
{% extends "snippets/base.html" %}
{% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/register/register.css' %}">
    {% endblock %}
{% block title %}
    <title>Password reset.</title>
{% endblock %}
    {% block content_block %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    <strong>{{message}}</strong>
                </div>
            {% endfor %}
        {% endif %}

{% if not pass_resettor.used %}
        <div class="form">
                <div id="login">
                  <h1>Password reset!</h1>
                  <form action="#" method="post">{% csrf_token %}
                    <div class="field-wrap">
                    <label>
                      Email<span class="req">*</span>
                    </label>
                    <input type="email"required autocomplete="off" name="email"/>
                  </div>
                  <button class="but button button-block">Reset</button>

                  <div class="instruction">
                    <p class="instruction_message">An email has sent to your requested email, this email is valid for 24 hours</p>
                  </div>
                  </form>
                </div>

              </div>
              {% elif pass_resettor.used and pass_resettor.active %}
              <div class="form">
                      <div id="login">
                        <h1>Password reset!</h1>

                        <form action="{% url 'register:pass_reset' %}" method="post">{% csrf_token %}

                          <div class="field-wrap">
                            <label>
                              Password<span class="req">*</span>
                            </label>
                            <input id="password1" type="password"required autocomplete="off" name="password1"/>
                          </div>

                          <div class="field-wrap">
                            <label>
                              ConfirmPassword<span class="req">*</span>
                            </label>
                            <input id="password2" type="password"required autocomplete="off" name="password2"/>
                          </div>

                        <button class="button button-block">Reset</button>
                        </form>
                      </div>
                    </div>
                {% else %}
                  <div class="form">
                    <h1>Password reset!</h1>
                      <p class="instruction">Session expired</p>
                  </div>
              {% endif %}


<script>
  window.onload = function(){
    {% if pass_resettor.used %}
    var password = document.getElementById("password1")
  , confirm_password = document.getElementById("password2");

function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}
password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;
{% endif %}

    $(".but").click(function(e){
      e.preventDefault()
        var resetMethodEndpoint = "{% url 'register:pass_reset' %}"
        var t = $("input[name=csrfmiddlewaretoken]").val();
        var email = $("input[name=email]").val();
        var data = {
            "email": email,
            'csrfmiddlewaretoken': t,
        }
        $.ajax({
            data: data,
            url: resetMethodEndpoint,
            method: "POST",
            success: function(data){
              if (data.error){
                alert("user does not exist")
              }
              if(!data.error) {
                $(".instruction_message").toggleClass()
              }
            },
            error: function(error){
                console.log(error)
            }
        })
  });
}
</script>
    {% endblock %}

register/templates/register/signin.html
{% extends "snippets/base.html" %}
{% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/register/register.css' %}">
    {% endblock %}
{% block title %}
    <title>Login.</title>
{% endblock %}
{% block meta %}
<meta name="description" content="Camping co India is a 4x4 off-roading company that takes you for an off-road adventure of a lifetime across various regions of India. ">
<meta name="keywords" content="login camping company, create, signup, camping company awesome">
{% endblock %}
    {% block content_block %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    <strong>{{message}}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form">

              <ul class="tab-group">
                <li class="tab active"><a href="#signup">Sign Up</a></li>
                <li class="tab"><a href="#login">Log In</a></li>
              </ul>

              <div class="tab-content">
                <div id="signup">

                  <form action="{% url 'register:signup' %}" method="post">{% csrf_token %}

                  <div class="top-row">
                    <div class="field-wrap">
                      <label>
                        Username<span class="req">*</span>
                      </label>
                      <input type="text" required autocomplete="off" name="username"/>
                    </div>

                    <div class="field-wrap">
                      <label>
                        Email<span class="req">*</span>
                      </label>
                      <input type="email"required autocomplete="off" name="email"/>
                    </div>
                  </div>

                  <div class="field-wrap">
                    <label>
                      Password<span class="req">*</span>
                    </label>
                    <input id="password1" type="password"required autocomplete="off" name="password1"/>
                  </div>

                  <div class="field-wrap">
                    <label>
                      ConfirmPassword<span class="req">*</span>
                    </label>
                    <input id="password2" type="password"required autocomplete="off" name="password2"/>
                  </div>
                      <div class="field-wrap">
                    <label>
                      Referral code (if any, code is 6 digit)
                    </label>
                    <input id="referral" type="text" autocomplete="off" name="slug"/>
                  </div>

                  <button class="button button-block">Get Started</button>

                  </form>

                </div>

                <div id="login">
                  <h1>Welcome Back!</h1>

                  <form action="{% url 'register:signin' %}" method="post">{% csrf_token %}

                    <div class="field-wrap">
                    <label>
                      Username/Email<span class="req">*</span>
                    </label>
                    <input type="text"required autocomplete="off" name="username"/>
                  </div>

                  <div class="field-wrap">
                    <label>
                      Password<span class="req">*</span>
                    </label>
                    <input type="password"required autocomplete="off" name="password"/>
                  </div>

                  <p class="forgot"><a href="{% url 'register:pass_reset' %}">Forgot Password?</a></p>

                  <input type="hidden" name="next" value="{{next}}">

                  <button class="button button-block">Log In</button>

                  </form>

                </div>

              </div>

        </div>
<script>
    window.onload = function(){
        var password = document.getElementById("password1")
      , confirm_password = document.getElementById("password2");

    function validatePassword(){
      if(password.value != confirm_password.value) {
        confirm_password.setCustomValidity("Passwords Don't Match");
      } else {
        confirm_password.setCustomValidity('');
      }
    }

    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;
    };
</script>
    {% endblock %}

register/templates/register/signup.html
{% extends "snippets/base.html" %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'css/rest.css' %}">{% endblock %}
{% block title %}
    <title>Sign up.</title>
{% endblock %}

{% block meta %}
<meta name="description" content="Camping company India is a 4x4 off-roading company that takes you for an off-road adventure of a lifetime across various regions of India. ">
<meta name="keywords" content="login camping company, create, signup, camping company awesome">
{% endblock %}
{% block content_block %}
    <div class="fix">
    <form class="stl" action="{% url 'register:signup' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="Fname">First Name:</label>
        <input type="text" class="form-control" id="Fname" name="firstname">
      </div>

      <div class="form-group">
        <label for="Lname">Last Name:</label>
        <input type="text" class="form-control" id="Lname" name="lastname">
      </div>

      <div class="form-group">
        <label for="Number">Phone number:</label>
        <input type="Number" class="form-control" id="Number" name="number">
      </div>

        <div class="form-group">
          <label for="email">Email address:</label>
          <input type="email" class="form-control" id="email" name="email">
        </div>

        <div class="form-group">
          <label for="username">Username:</label>
          <input type="text" class="form-control" id="username" name="username">
        </div>


        <div class="form-group">
          <label for="pwd">Password:</label>
          <input type="password" class="form-control" id="pwd" name="password1">
        </div>

        <div class="form-group">
          <label for="pwd">Re enter Password:</label>
          <input type="password" class="form-control" id="pwd" name="password2">
        </div>

    <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
  {% endblock %}

register/templates/register/welcome.html
{% extends "snippets/base.html" %}
    {% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/register/welcome.css' %}">
    {% endblock %}

{% block title %}
    <title>Fill personal detail.</title>
{% endblock %}

{% block content_block %}
        {% if messages %}
            {% for message in messages %}
                <div style="text-align: center; margin-top:4%;" class="alert alert-warning">
                    <strong>{{message}}</strong>
                </div>
            {% endfor %}
        {% endif %}
<br>
<br>

<h1 style="text-align:center; color:white;">Welcome {{request.user}}</h1>
<h3 style="text-align:center; color:white;">You are almost Done</h3>
        <form method="POST" action="{% url 'register:welcome' %}">{% csrf_token %}
  <div id="msform">

    <ul id="progressbar">
      <li class="active">Account Details</li>
      <li>Personal Details</li>
      <li>Registered</li>
    </ul>

    <fieldset>
      <h2 class="fs-title">Account Details</h2>
      <h3 class="fs-subtitle">For More Awesome Adventure</h3>
      <input id="email" type="text" name="license_number" placeholder="license_number" />
      <input id="city" type="text" name="city" placeholder="City" />
      <input id="nickname" type="text" name="nickname" placeholder="NICKNAME" />
      <textarea id="about" name="about" placeholder="ABOUT YOURSELF" ></textarea>
      <input type="button" name="next" class="next action-button" value="Next" />
    </fieldset>
    <fieldset>
      <h2 class="fs-title">Personal Detail</h2>
      <h3 class="fs-subtitle">We will never sell it</h3>
      <input id="fname" type="text" name="fname" placeholder="First Name" />
      <input id="lname" type="text" name="lname" placeholder="Last Name" />
      <input id="number" type="number" name="number" placeholder="Phone" />
      <textarea id="address" name="address" placeholder="Address"></textarea>
      <input type="button" name="previous" class="previous action-button" value="Previous" />
      <input type="button" name="next" class="next action-button" value="Next" />
    </fieldset>
    <fieldset>
      <h2 class="fs-title">Success</h2>
        <h2 class="fs-subtitle">By clicking Submit, you agree on our <a target="_blank" href="{% url 'app:terms_condition' %}">terms and condition.</a></h2>
        <h3 class="fs-subtitle">Thank you for registering with us.</h3>
      <input type="submit" name="submit" class="submit action-button" value="Submit" />
    </fieldset>
  </div>
</form>

{% endblock %}