app/urls.py
from django.conf.urls import url
from app import views

app_name = "app"

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^about/$', views.about, name="about"),
    url(r'^all_user/$', views.all_user, name="all_user"),
    url(r'^detail_user/(?P<pk>\d+)$', views.detail_user, name="detail_user"),
    url(r'^findus/$', views.findus, name="findus"),
    url(r'^represent/$', views.represent, name="represent"),
    url(r'^calender/$', views.calender, name="calender"),
    url(r'^status/(?P<pk>\d+)/show/$', views.show_status, name="show_status"),
    url(r'^terms_condition/$', views.terms_condition, name="terms_condition"),
    url(r'^faq/$', views.faq, name="faq"),
    url(r'^damage_charges/$', views.damage_charges, name="damage_charges"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),

]

genie/urls.py
from django.conf.urls import url
from django.urls import path
from genie.views import create,detail

app_name = "genie"

urlpatterns = [
           url('creation/', create, name='create'),
           # path('displaying/', display , name='display'),
           path('detail/', detail , name='detail')

       ]

genie/models.py
from django.db import models
from django.contrib.auth.models import User
from vehicle.models import Book

# Create your models here.
class mainFrame(models.Model):
	object_id= models.ForeignKey(Book, on_delete=models.CASCADE)
	front_image = models.ImageField(upload_to="genie/mainframe", blank=True, null=True)
	back_image = models.ImageField(upload_to="genie/mainframe", blank=True, null=True)
	left_image = models.ImageField(upload_to="genie/mainframe", blank=True, null=True)
	right_image = models.ImageField(upload_to="genie/mainframe", blank=True, null=True)

	def __str__(self):
		return self.object_id

class vehicleCleanliness(models.Model):
	object_id= models.ForeignKey(Book, on_delete=models.CASCADE)
	first_image = models.ImageField(upload_to="genie/cleanliness", blank=True, null=True)
	second_image = models.ImageField(upload_to="genie/cleanliness", blank=True, null=True)
	third_image = models.ImageField(upload_to="genie/cleanliness", blank=True, null=True)
	fourth_image = models.ImageField(upload_to="genie/cleanliness", blank=True, null=True)

	def __str__(self):
		return self.object_id

class photos(models.Model):
	object_id= models.ForeignKey(Book, on_delete=models.CASCADE)
	first_image = models.ImageField(upload_to="genie/photo", blank=True, null=True)
	second_image = models.ImageField(upload_to="genie/photo", blank=True, null=True)

	def __str__(self):
		return self.object_id

genie/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from genie.models import mainFrame, vehicleCleanliness, photos
from vehicle.models import Book


# Create your views here.

def create(request):
	print('i am here')
	return render(request,"genie/index.html")

# def showing(request):


def detail(request):
	book = Book.objects.all()
	return render(request,"genie/landing.html",{"book":book})

genie/templates/genie/index.html
  <!DOCTYPE html>
  <html>
<head>

      <meta http-equiv="content-type" content="text/html;charset =UTF-8">
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial--scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

        <title> Images Upload</title>
      </head>


<!---  Car images --->
  <form action="{% url 'genie:create' %}" method="post">
    {% csrf_token %}
    <label for="front"> Front view </label>
<input type="file" name="pic" accept="image/*">
   <input type="submit"><br><br><br><br>

   <label for="rear"> Rear view </label>
<input type="file" name="image" accept="image/*">
  <input type="submit"><br><br><br><br>

  <label for="left"> Left side view </label>
<input type="file" name="leftside" accept="image/*">
 <input type="submit"><br><br><br><br>

 <label for="right"> Right view </label>
<input type="file" name="rightside" accept="image/*">
<input type="submit"><br><br><br><br>

<!---  Vehicle Cleanliness  --->

<label for="tent_interior"> Tent Interior </label>
<input type="file" name="inside" accept="image/*">
<input type="submit"><br><br><br><br>

<label for="tent_exterior"> Tent Exterior </label>
<input type="file" name="outside" accept="image/*">
<input type="submit"><br><br><br><br>

<label for="inside_car"> Car Interior </label>
<input type="file" name="interior" accept="image/*">
<input type="submit"><br><br><br><br>

<label for="outside_car"> Car Exterior </label>
<input type="file" name="exterior" accept="image/*">
<input type="submit"><br><br><br><br>

<!---   Customer  Photo ID  --->
<label for="Front_id"> Photo ID Front </label>
<input type="file" name="front" accept="image/*">
<input type="submit"><br><br><br><br>

<label for="Back_id"> Photo ID  Back </label>
<input type="file" name="exterior" accept="image/*">
<input type="submit"><br><br><br><br>



</form>

     </body>

  </html>

genie/templates/genie/landing.html
<h1> Hello there</h1>

{% for x in book %}
	<p>{{x.car_name}}</p>
	<p>{{x.check_out_date}}</p>
	<p>{{x.check_in_date}}</p>
{% endfor %}