app/urls.py
from django.conf.urls import url
from app import views

app_name = "app"

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^about/$', views.about, name="about"),
    url(r'^all_user/$', views.all_user, name="all_user"),
    url(r'^detail_user/(?P<pk>\d+)$', views.detail_user, name="detail_user"),
    url(r'^findus/$', views.findus, name="findus"),
    url(r'^represent/$', views.represent, name="represent"),
    url(r'^calender/$', views.calender, name="calender"),
    url(r'^status/(?P<pk>\d+)/show/$', views.show_status, name="show_status"),
    url(r'^terms_condition/$', views.terms_condition, name="terms_condition"),
    url(r'^faq/$', views.faq, name="faq"),
    url(r'^damage_charges/$', views.damage_charges, name="damage_charges"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),

]

blog/urls.py
from django.conf.urls import url
from blog.views import (all_blog, blog_detail,
                        event, event_form)

app_name = "blog"

urlpatterns = [
    url(r'^$', all_blog, name="all_blog"),
    url(r'^event/$', event, name="event"),
    url(r'^event_form/$', event_form, name="event_form"),
    url(r'^(?P<slug>[\w-]+)/$', blog_detail, name="blog_detail"),

]

customer/urls.py
from django.conf.urls import url
from customer.views import (user_page, book,
                            custom_itinerary,
                            create_itinerary,
                            delete_itinerary,
                            trip_detail,
                            form)

app_name = "customer"

urlpatterns = [
    url(r'^$', user_page, name="user_page"),
    url(r'^create/$', create_itinerary, name="create_itinerary"),
    url(r'^book/(?P<pk>\d+)/success/$', book, name="book"),
    url(r'^itinerary/delete/$', delete_itinerary, name="delete_itinerary"),
    url(r'^itinerary/$', custom_itinerary, name="custom_itinerary"),
    url(r'^trip_detail/$', trip_detail, name="trip_detail"),
    url(r'^form/$', form, name="form"),

]

register/urls.py
from django.conf.urls import url
from register.views import (signup, signin, sign_out,
                            welcome, pass_reset,pass_rediretor)


app_name = "register"

urlpatterns = [
    url(r'^signup/$', signup, name="signup"),
    url(r'^login/$', signin, name="signin"),
    url(r'^logout/$', sign_out, name="signout"),
    url(r'^welcome/$', welcome, name="welcome"),
    url(r'^reset/(?P<slug>[\w-]+)/$', pass_rediretor, name="pass_rediretor"),
    url(r'^reset/$', pass_reset, name="pass_reset"),

]

vehicle/urls.py
from django.conf.urls import url
from vehicle.views import (vehicles, vehicle_create_check,
                           vehicle_update_check, vehicle_info,vehicle)

app_name = "vehicles"

urlpatterns = [
    url(r'^$', vehicles, name="vehicles"),
    url(r'^(?P<pk>\d+)/create/$', vehicle_create_check, name="vehicle_create_check"),
    url(r'^(?P<pk>\d+)/update/$', vehicle_update_check, name="vehicle_update_check"),
    url(r'^vehicle_info/$', vehicle_info, name="vehicle_info"),
    url(r'^all/$', vehicle, name="vehicle"),
]

templates/snippets/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '677707006058508');
  fbq('track', 'PageView');
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149832658-1"></script>
    <script>  window.dataLayer = window.dataLayer || []; 
    function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());
    gtag('config', 'UA-149837617-1');</script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=677707006058508&ev=PageView&noscript=1"/>
    </noscript>

    {% block title %}

    {% endblock %}

    {% block meta %}

    {% endblock %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" >
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favi/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favi/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favi/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favi/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favi/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favi/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favi/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favi/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favi/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favi/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favi/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favi/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favi/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favi/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favi/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#0EAC8D">

    {% include "snippets/css.html" %}

    {% block css %}

    {% endblock %}


</head>
<body>
    {% include "snippets/navbar.html" %}

    {% block content_block %}

    {% endblock %}

    {% include "snippets/js.html" %}

</body>
</html>

templates/snippets/css.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather+Sans&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
<link href="{% static 'css/calender/jquery.datetimepicker.css' %}" rel="stylesheet">
<link href="{% static 'css/table.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

templates/snippets/footer.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/home/footer.css' %}">
<div class="mar">
    <div class="box">
        <footer class= "footer">
            <a href="https://www.youtube.com/channel/UC6mvUrWd2m4KbokMSALM0Hw"><i class="fab fa-youtube"></i></a>
            <a href="https://www.facebook.com/thecampingco"><i class="fab fa-facebook-square"></i> </a>
            <a href="https://www.instagram.com/camping_co"><i class="fab fa-instagram"></i></a>
            <div class="cont">
                <div><a href="{% url 'app:terms_condition' %}"><strong>Terms & conditions</strong></a></div>
                <div> Camping Co. @ 2018</div>
            </div>
        </footer>
    </div>
</div>

templates/snippets/js.html
{% load staticfiles %}
    <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script defer src="{% static 'js/popper.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <script defer src="{% static 'js/easing.js' %}"></script>
    <script defer src="{% static 'js/vehicles.js' %}"></script>
    <script defer src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
    <script defer src="{% static 'js/data.js' %}"></script>
    <script defer src="{% static 'js/bootable.js' %}"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

templates/snippets/navbar.html
{% url 'app:home' as home_url %} {% url 'customer:user_page' as customer_url %} {% url 'destination:circuits' as circuits_url %} {% url 'app:about' as about_url %} {% url 'destination:destinations' as destination_url %} {% url 'vehicle:vehicle' as vehicle_url %} {% url 'app:findus' as findus_url %} {% url 'register:signout' as signout_url %} {% url 'register:signin' as register_url %} {% url 'app:faq' as faq_url %} {% url 'blog:all_blog' as blog_url %} {% url 'blog:event' as event_url %} {% url 'app:represent' as represent_url %} {% load staticfiles %}

<header>
    <link rel="stylesheet" href="{% static 'css/home/header.css' %}">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{% url 'app:home' %}"><img src="{% static 'images/favi/apple-icon-57x57.png' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated and not user.is_superuser %}
                <li class="nav-item {% if request.path == customer_url  %}active{% endif %}"><a class="nav-link" href="{{customer_url}}">Profile</a></li>
                {% elif user.is_superuser %}
                <li class="nav-item {% if request.path == represent_url  %}active{% endif %}"><a class="nav-link" href="{{represent_url}}">Represent</a></li>
                {% endif %}
                <li class="nav-item {% if request.path == vehicle_url  %}active{% endif %}"><a class="nav-link" href="{{vehicle_url}}">Campers</a></li>
                <li class="nav-item {% if request.path == destination_url  %}active{% endif %}"><a class="nav-link" href="{{destination_url}}">Campsites</a></li>
                <li class="nav-item {% if request.path == circuits_url  %}active{% endif %}"><a class="nav-link" href="{{circuits_url}}">Circuits</a></li>
                <li class="nav-item {% if request.path == blog_url  %}active{% endif %}"><a class="nav-link" href="{{blog_url}}">Journal</a></li>
                <li class="nav-item {% if request.path == findus_url  %}active{% endif %}"><a class="nav-link" href="{{findus_url}}">Contact</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item {% if request.path == signout_url  %}active{% endif %}"><a class="nav-link" href="{{signout_url}}">Logout</a></li>
                {% else %}
                <li class="nav-item {% if request.path == register_url  %}active{% endif %}"><a class="nav-link" href="{{register_url}}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/snippets/test.html
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
    <a class="navbar-brand {% if request.path == home_url  %}active{% endif %}" href="{{home_url}}"><img src="{% static 'images/favicon/apple-icon-57x57.png' %}"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="navbar-nav mx-5 mr-auto">
            {% if user.is_authenticated and not user.is_superuser %}
                <li class="nav-item {% if request.path == customer_url  %}active{% endif %}"><a class="nav-link" href="{{customer_url}}">Profile</a></li>
            {% elif user.is_superuser %}
                <li class="nav-item {% if request.path == represent_url  %}active{% endif %}"><a class="nav-link" href="{{represent_url}}">Represent</a></li>
            {% endif %}
            <li class="nav-item {% if request.path == about_url  %}active{% endif %}"><a class="nav-link" href="{{about_url}}">About</a></li>
            <li class="nav-item {% if request.path == destination_url  %}active{% endif %}"><a class="nav-link" href="{{destination_url}}">Destinations</a></li>
            <li class="nav-item {% if request.path == vehicle_url  %}active{% endif %}"><a class="nav-link" href="{{vehicle_url}}">Vehicles</a></li>
            <li class="nav-item {% if request.path == blog_url  %}active{% endif %}"><a class="nav-link" href="{{blog_url}}">Blog</a></li>
            <li class="nav-item {% if request.path == event_url  %}active{% endif %}"><a class="nav-link" href="{{event_url}}">Events</a></li>
            <li class="nav-item {% if request.path == findus_url  %}active{% endif %}"><a class="nav-link" href="{{findus_url}}">Contact</a></li>
            {% if user.is_authenticated %}
              <li class="nav-item {% if request.path == signout_url  %}active{% endif %}"><a class="nav-link" href="{{signout_url}}">Logout</a></li>
            {% else %}
            <li class="nav-item {% if request.path == register_url  %}active{% endif %}"><a class="nav-link" href="{{register_url}}">Login</a></li>
            {% endif %}
            <li class="nav-item {% if request.path == faq_url  %}active{% endif %}"><a class="nav-link" href="{{faq_url}}">FAQ</a></li>
        </ul>
    </div>
    </div>
  </nav>